version: '3.5'
services:
  mysql:
    # Version should match production
    image: mysql:8.0.23
    cap_add:
      - SYS_NICE
    env_file: .env
    command: "mysqld"
    ports:
      - 3306:3306
    tmpfs:
      - /var/lib/mysql
    volumes:
      - ./baseline/:/docker-entrypoint-initdb.d